test_01:
  target: kbc_dev_chocho
  outputs:
    kbc_prod:
       type: "{{ env_var('DBT_KBC_TYPE') }}"              #snowflake 
       user: "{{ env_var('DBT_KBC_USER') }}"              #KEBOOLA_WORKSPACE_410407633
       password: "{{ env_var('DBT_KBC_PASSWORD') }}"      #xxxxx
       schema: "{{ env_var('DBT_KBC_SCHEMA') }}"          #WORKSPACE_410407633
       warehouse: "{{ env_var('DBT_KBC_WAREHOUSE') }}"    #KEBOOLA_PROD
       database: "{{ env_var('DBT_KBC_DATABASE') }}"      #KEBOOLA_33
       account: "{{ env_var('DBT_KBC_ACCOUNT') }}"        #keboola.eu-central-1
    kbc_dev_chocho:
       type: "{{ env_var('DBT_KBC_DEV_CHOCHO_TYPE') }}"
       user: "{{ env_var('DBT_KBC_DEV_CHOCHO_USER') }}"
       password: "{{ env_var('DBT_KBC_DEV_CHOCHO_PASSWORD') }}"
       schema: "{{ env_var('DBT_KBC_DEV_CHOCHO_SCHEMA') }}"
       warehouse: "{{ env_var('DBT_KBC_DEV_CHOCHO_WAREHOUSE') }}"
       database: "{{ env_var('DBT_KBC_DEV_CHOCHO_DATABASE') }}"
       account: "{{ env_var('DBT_KBC_DEV_CHOCHO_ACCOUNT') }}"
    kbc_dev_padak:
       type: "{{ env_var('DBT_KBC_DEV_PADAK_TYPE') }}"
       user: "{{ env_var('DBT_KBC_DEV_PADAK_USER') }}"
       password: "{{ env_var('DBT_KBC_DEV_PADAK_PASSWORD') }}"
       schema: "{{ env_var('DBT_KBC_DEV_PADAK_SCHEMA') }}"
       warehouse: "{{ env_var('DBT_KBC_DEV_PADAK_WAREHOUSE') }}"
       database: "{{ env_var('DBT_KBC_DEV_PADAK_DATABASE') }}"
       account: "{{ env_var('DBT_KBC_DEV_PADAK_ACCOUNT') }}"
  
#export DBT_KBC_DATABASE="KEBOOLA_33"
#export DBT_KBC_SCHEMA="WORKSPACE_410407633"
#export DBT_KBC_WAREHOUSE="KEBOOLA_PROD"
#export DBT_KBC_ACCOUNT="keboola.eu-central-1"
#export DBT_KBC_TYPE="snowflake"
#export DBT_KBC_USER="KEBOOLA_WORKSPACE_410407633"
#export DBT_KBC_PASSWORD="xxxx"
